### ISSUE TITLE
Error when running conan install

### ISSUE THREAD

**Issue by niucool** [blockspacer/chromium_base_conan#1]
Hi, I just want to build the your project, but I got the following error:

ERROR: Error loading conanfile at 'd:\Projects\chromium_base_conan\conanfile.py': Version range '~=0.0' from requirement 'conan_build_helper/[~=0.0]@conan/stable' required by 'python_require' could not be resolved in local cache

Could you please tell me how to fix it?

**Comment by blockspacer** [comment]
See for details README file of flextool https://github.com/blockspacer/flextool

You can use buildConanThirdparty.cmake script to download and install conan packages.
```
# NOTE: don't forget to re-run `conan install` or `conan create` after command below
# NOTE: change `build_type=Debug` to `build_type=Release` in production
cmake -DEXTRA_CONAN_OPTS="--profile;clang;-s;build_type=Debug;-s;cling_conan:build_type=Release;--build;missing" -P tools/buildConanThirdparty.cmake
```
All requirements can be found in my github repos list.

You can use conan create to install only required packages (cling is not required to build chromium base and can be skipped)

**Comment by niucool** [comment]
Got it, let me try. Thanks a lot.

**Comment by blockspacer** [comment]
Updated https://github.com/blockspacer/chromium_base_conan/blob/master/README.md

Quote:


> ## Before build (dependencies)
> 
> Create clang conan profile https://docs.conan.io/en/1.34/reference/profiles.html#examples
> 
> Re-build dependencies:
> 
> ```bash
> git clone https://github.com/blockspacer/conan_github_downloader.git ~/conan_github_downloader
> 
> cmake \
>   -DSCRIPT_PATH="$PWD/get_conan_dependencies.cmake"\
>   -DEXTRA_CONAN_OPTS="--profile;clang\
> ;-s;build_type=Debug\
> ;-s;cling_conan:build_type=Release\
> ;-s;llvm_tools:build_type=Release\
> ;--build;missing" \
>   -P ~/conan_github_downloader/conan_github_downloader.cmake
> ```


> ## HOW TO BUILD FROM SOURCE
> 
> ```bash
> # NOTE: change `build_type=Debug` to `build_type=Release` in production
> CONAN_REVISIONS_ENABLED=1 \
>     CONAN_VERBOSE_TRACEBACK=1 \
>     CONAN_PRINT_RUN_COMMANDS=1 \
>     CONAN_LOGGING_LEVEL=10 \
>     GIT_SSL_NO_VERIFY=true \
>     conan create . \
>         conan/stable \
>         -s build_type=Debug \
>         -s llvm_tools:build_type=Release \
>         --profile clang \
>         --build missing \
>         --build cascade \
>         -e chromium_base:enable_tests=True \
>         -o chromium_base:use_alloc_shim=True \
>         -o chromium_base:shared=True \
>         -o chromium_tcmalloc:use_alloc_shim=True \
>         -o perfetto:is_hermetic_clang=False \
>         -o openssl:shared=True
> 
> # clean build cache
> conan remove "*" --build --force
> ```
